#!/bin/sh
# File generated by ocamlbuild

cd /home/student/share/496/hw4

rm -f ast.cmi
rm -f ast.cmo
rm -f checker.cmi
rm -f checker.cmo
rm -f ds.cmi
rm -f ds.cmo
rm -f lexer.cmi
rm -f lexer.cmo
rm -f lexer.ml
rm -f parser.cmi
rm -f parser.cmo
rm -f parser.ml
# Also clean the script itself
rm -f /home/student/share/496/hw4/_build/sanitize.sh
